In [1]:
# This file uses sentences from ClaimsExtractedByUs to learn the sentence-look_up_value distribution
# considering unique (sentence, claim) pairs

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.pipeline import FeatureUnion
import numpy as np

In [3]:
path = "data/annotated_11_19_2019/ClaimsExtractedByUs.csv"

In [4]:
df = pd.read_csv(path, encoding="latin1")

In [5]:
df

Text  \
0     The Sustainable Development Scenario starts wi...   
1     The Sustainable Development Scenario starts wi...   
2     The Sustainable Development Scenario starts wi...   
3     For the first time the number of people withou...   
4     For the first time the number of people withou...   
5     For the first time the number of people withou...   
6     Despite significant steps forward in Kenya, Et...   
7                            Total electrification rate   
8                            Total electrification rate   
9                            Total electrification rate   
10                           Total electrification rate   
11    Today energy-related outdoor air pollution lea...   
12    Today energy-related outdoor air pollution lea...   
13    Significant new policies have been announced t...   
14    Energy-related carbon dioxide (CO2) emissions ...   
15    Energy-related carbon dioxide (CO2) emissions ...   
16    Energy-related carbon dioxide (CO2) emissions ...   
17    Energy-related carbon dioxide (CO2) emissions ...   
18    Energy-related carbon dioxide (CO2) emissions ...   
19    Energy-related carbon dioxide (CO2) emissions ...   
20    650 million people will still lack electricity...   
21    650 million people will still lack electricity...   
22    650 million people will still lack electricity...   
23    Lower levels of air pollutants will be insuffi...   
24    And CO2 emissions are set to rise gradually to...   
25    premature deaths from outdoor air pollution ar...   
26    And CO2 levels decline rapidly in line with th...   
27    And a move away from traditional use of biomas...   
28    And a move away from traditional use of biomas...   
29                                 HAP premature deaths   
...                                                 ...   
1776  If waste from all those who lack access to saf...   
1777  If current consumption patterns persist, globa...   
1778  The energy sectoräó»s share of total global wa...   
1779  The energy sectoräó»s share of total global wa...   
1780  The energy sectoräó»s share of total global wa...   
1781  The energy sectoräó»s share of total global wa...   
1782  In a  scenario water withdrawals by the energy...   
1783  In a decarbonisation scenario water withdrawal...   
1784                                              #REF!   
1785  Shifting the emphasis away from an approach fo...   
1786  Shifting the emphasis away from an approach fo...   
1787  However, the higher level of consumption (+10%...   
1788  In 2016 the energy sector withdrew around 340 ...   
1789  In 2016 the energy sector withdrew around 360 ...   
1790  The power sector is responsible for the majori...   
1791  The power sector is responsible for the majori...   
1792  Primary energy production is responsible  for ...   
1793  Primary energy production is responsible  for ...   
1794  Primary energy production is responsible  for ...   
1795  In the Sustainable Development Scenario, globa...   
1796  In the Sustainable Development Scenario, globa...   
1797  In the Sustainable Development Scenario, globa...   
1798  In the Sustainable Development Scenario, globa...   
1799  Increased energy efficiency, the move away fro...   
1800  Increased energy efficiency, the move away fro...   
1801  This helps with progress towards SDG Target 6....   
1802  This helps with progress towards SDG Target 6....   
1803  Ensuring 2.1 billion people  have access to cl...   
1804  Ensuring 2.1 billion people  have access to cl...   
1805  Ensuring 2.1 billion people  have access to cl...   

                                        Published value  \
0                                                     7   
1                                                   3.9   
2                                                    13   
3                                    For the first time   
4                                  fell below 1 billion   
5                                is de

In [6]:
df_lookup = df[df["Fixed_Formulas"].str.contains("LOOKUP")]

In [7]:
df_lookup

Text  \
18    Energy-related carbon dioxide (CO2) emissions ...   
19    Energy-related carbon dioxide (CO2) emissions ...   
32    Stronger policy action leads to substantially ...   
33    Stronger policy action leads to substantially ...   
34    Stronger policy action leads to substantially ...   
35    Stronger policy action leads to substantially ...   
36    Stronger policy action leads to substantially ...   
37    Stronger policy action leads to substantially ...   
39    Stronger policy action leads to substantially ...   
40    Stronger policy action leads to substantially ...   
42    Stronger policy action leads to substantially ...   
43    Stronger policy action leads to substantially ...   
53    for the first time the number of people withou...   
54    for the first time the number of people withou...   
55    for the first time the number of people withou...   
56    for the first time the number of people withou...   
57    for the first time the number of people withou...   
58    for the first time the number of people withou...   
59    for the first time the number of people withou...   
60    for the first time the number of people withou...   
64    In sub-Saharan Africa 600 million people are s...   
72    Energy-related carbon dioxide (CO2) emissions ...   
73    Energy-related carbon dioxide (CO2) emissions ...   
74    Energy-related carbon dioxide (CO2) emissions ...   
75    Energy-related carbon dioxide (CO2) emissions ...   
77    Energy-related carbon dioxide (CO2) emissions ...   
78    Energy-related carbon dioxide (CO2) emissions ...   
80    Energy-related carbon dioxide (CO2) emissions ...   
82                                                    0   
83                                                    0   
...                                                 ...   
1648  The proportion is set to remain almost unchang...   
1650  In the Sustainable Development Scenario, effor...   
1651  In the Sustainable Development Scenario, effor...   
1652  In the Sustainable Development Scenario, effor...   
1666  In the Sustainable Development Scenario, a com...   
1667  In the Sustainable Development Scenario, a com...   
1669  In the Sustainable Development Scenario, a com...   
1670  In the Sustainable Development Scenario, a com...   
1671  In the Sustainable Development Scenario, a com...   
1672  In the Sustainable Development Scenario, a com...   
1674  In the Sustainable Development Scenario, a com...   
1675  In the Sustainable Development Scenario, a com...   
1676  In the Sustainable Development Scenario, a com...   
1677  In the Sustainable Development Scenario, a com...   
1679  The share of electricity increases substantial...   
1680  The share of electricity increases substantial...   
1681  The share of electricity increases substantial...   
1682  The share of electricity increases substantial...   
1684  The share of electricity increases substantial...   
1685  The share of electricity increases substantial...   
1686  The share of electricity increases substantial...   
1687  The share of electricity increases substantial...   
1689  The share of electricity increases substantial...   
1690  The share of electricity increases substantial...   
1691  The share of electricity increases substantial...   
1692  The share of electricity increases substantial...   
1694  Support  for renewable electricity has led to ...   
1695  Support  for renewable electricity has led to ...   
1750  For example, mini-grids äóñ which provide elec...   
1751  For example, mini-grids äóñ which provide elec...   

                          Published value Author calc Value  \
18                   increased deployment        723.284262   
19                   increased deployment       770.4351901   
32                   substantially higher       38.27872429   
33                   substantially higher       309.3837303   
34                   substantially higher       224.3022014   
35            

In [8]:
# drop duplicates
df_lookup_no_dups = df_lookup.drop_duplicates(subset="Text")

In [9]:
df_lookup_no_dups

Text  \
18    Energy-related carbon dioxide (CO2) emissions ...   
32    Stronger policy action leads to substantially ...   
53    for the first time the number of people withou...   
64    In sub-Saharan Africa 600 million people are s...   
72    Energy-related carbon dioxide (CO2) emissions ...   
82                                                    0   
91    Substantial reductions in major air pollutant ...   
99    Energy-related CO2 emissions peak and then dec...   
110   Given expected strong population growth over t...   
115   The cheapest way to achieve universal electric...   
127   The cheapest way for people to gain access to ...   
139   In the Sustainable Development Scenario, emiss...   
154   Emissions of NOX, which occur predominantly in...   
165   Universal access to clean cooking reduces resi...   
196   In the Sustainable Development Scenario, globa...   
208   In 2017 CO2 and methane emissions from energy ...   
215   The largest by some measure is coal-fired powe...   
223                                         Oil and gas   
248                                              trucks   
279   The largest emitter in 2040 becomes cement pro...   
283   Emissions from cars halve, despite the number ...   
300   Overall, the proportion of emissions from the ...   
307   Energy consumption patterns shift driven first...   
317   Within this more efficient energy system, ther...   
330   Industry is the only end-use sector to see a s...   
354   Total energy consumption in the transport sect...   
394   Improved energy efficiency means energy use in...   
406   A further marked change is a sharp reduction o...   
453   Overall primary energy demand stays flat in th...   
459   The shifts in energy consumption and power gen...   
...                                                 ...   
1462  Electricity tariffs were reduced in Thailand, ...   
1472  China has phased out gas subsidies in the indu...   
1476  Subsidies have risen slightly in 2017, but by ...   
1481  Methane emissions from the oil and gas sector ...   
1487  Over 80% of the emissions come from upstream p...   
1493  Methane emissions äóñ particularly for upstrea...   
1509  Implementation of 5 measures at no net economi...   
1518  Around a third of the additional reductions in...   
1520  The remaining two-thirds come from going furth...   
1532  Investment in renewables is by itself the seco...   
1544  The scenario implies a profound and rapid shif...   
1558  cement, iron and steel, chemicals and aluminiu...   
1582  Even assuming that every householdäó»s energy ...   
1586  LPG use for clean cooking access has a similar...   
1591  Further, people living in sub-Saharan Africa, ...   
1594  In the Sustainable Development Scenario, despi...   
1597  Renewables are the most cost-effective route f...   
1601  CO2 emissions would be lower in 2040 in sub-Sa...   
1604  Achieving universal access to modern energy do...   
1623  In the Sustainable Development Scenario, CO2 e...   
1629  The transport sector is currently the biggest ...   
1631  The additional transport NOx reductions in the...   
1638  By 2040, the majority of additional reductions...   
1642  ¥¬ for PM2.5 emissions, more than half of cur...   
1647  The proportion is set to remain almost unchang...   
1650  In the Sustainable Development Scenario, effor...   
1666  In the Sustainable Development Scenario, a com...   
1679  The share of electricity increases substantial...   
1694  Support  for renewable electricity has led to ...   
1750  For example, mini-grids äóñ which provide elec...   

                         Published value Author calc Value  \
18                  increased deployment        723.284262   
32                  substantially higher       38.27872429   
53                    for the first time        1422.12966   
64                    600 million people         580.67282   
72     for the first time in three years       32138.38726   
82    increased depl

In [10]:
# Experiment 1
# The features will be the text and the label will be the lookup-value here

In [11]:
from src.tokenizer.tokenizer_driver import TokenizerDriver
from src.featurizer.feature_extractor import FeatureExtractor

In [12]:
tok_driver = TokenizerDriver()
featurizer = FeatureExtractor(mode="tfidf")

In [13]:
claim_sents = list(df_lookup_no_dups["Text"])

In [14]:
tokenized_sents = tok_driver.tokenize_claims(claim_sents)

In [15]:
features = featurizer.featurize_claims(tokenized_sents)

In [16]:
features.shape

(140, 2444)

In [17]:
labels = list(df_lookup_no_dups["Look-up value"])

In [18]:
len(labels)

140

In [19]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.20, random_state=42)

In [20]:
X_train.shape, len(y_train), X_test.shape, len(y_test)

((112, 2444), 112, (28, 2444), 28)

In [21]:
model = LinearSVC()

In [22]:
model.fit(X_train, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [23]:
final_model = CalibratedClassifierCV(base_estimator=model, cv="prefit")

In [24]:
final_model.fit(X_train, y_train)

CalibratedClassifierCV(base_estimator=LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0),
            cv='prefit', method='sigmoid')

In [25]:
def _linear_scale_confidence(confidences):
    """
    return the ratio of prob according to the sum of top n probabilities for the predicted intents.
    if probs = [p1, p2, p3] then the return probabilities will be scaled as
    [p1/sum(p1,p2,p3), p2/sum(p1,p2,p3), p3/sum(p1,p2,p3)]
    Args:
        confidences: probabilities of intents
    Returns:
        numpy array: the scaled confidences
    """
    s = np.sum(confidences)
    return confidences/s

In [26]:
def predict_utt_top_n(mod, featurized_utt, n=3):
    """
    predict the top3 intents along with the confidence probability for each one.
    Note that model.classes_ contains the trained labels in alphabetical order. Here, we sort the
    confidences together with the labels, and return the top3 from this sorted order
    Args:
        featurized_utt (str): featurized and tokenized single utterance
    Returns:
        One list of strings and one list of floats
    """
    raw_confidences = mod.predict_proba(featurized_utt)[0]
    # indices of sorted confidences from high to low confidence
    sorted_conf_idx = np.argsort(raw_confidences)[::-1][:n]
    labels = np.take(mod.classes_, sorted_conf_idx)
    confidences = np.take(raw_confidences, sorted_conf_idx)
    scaled_confidences = _linear_scale_confidence(confidences)

    return labels, scaled_confidences

In [27]:
temp = X_test[0]

In [28]:
predict_utt_top_n(final_model, temp.reshape(1, -1))

(array(['SubsidyTotal_World', 'CO2TPEDtotal', 'PGINrenew'], dtype='<U32'),
 array([0.46084942, 0.39177897, 0.14737161]))

In [29]:
predictions = [predict_utt_top_n(final_model, test.reshape(1, -1), n=5) for test in X_test]

In [30]:
predictions

[(array(['SubsidyTotal_World', 'CO2TPEDtotal', 'PGINrenew', 'CO2PGINcoal',
         'CO2_TPED_IP_total'], dtype='<U32'),
  array([0.37595172, 0.31960543, 0.1202228 , 0.09787882, 0.08634122])),
 (array(['InvAccess_cookingtotal', 'PGINrenew', 'AccessPGInvInfra_total',
         'TPEDperGDP', 'PM_Bldg_Total'], dtype='<U32'),
  array([0.41828627, 0.17121213, 0.16958955, 0.12451565, 0.1163964 ])),
 (array(['TPEDgas', 'PGINrenew', 'PGCap_coal', 'PGOUTtotal',
         'PM_Bldg_Total'], dtype='<U32'),
  array([0.21492098, 0.2047772 , 0.19995913, 0.19163121, 0.18871147])),
 (array(['PGINrenew', 'PGOUTtotal', 'ElecGenElecOnly_Coal_Subcritical',
         'INDIC_CO2_Elec_g_per_kWh', 'TPEDperGDP'], dtype='<U32'),
  array([0.25922123, 0.23523486, 0.1879944 , 0.15986291, 0.1576866 ])),
 (array(['TFCtotal', 'PGINrenew', 'TPEDperGDP', 'InvCosts_IND_Eff_Total',
         'TFCelec'], dtype='<U32'),
  array([0.30423608, 0.26883416, 0.15053009, 0.13955997, 0.1368397 ])),
 (array(['CO2TPEDtotal', 'PGINrenew',

In [31]:
len(y_test)

28

In [35]:
len(prediction_labels)

28

In [33]:
prediction_labels = [pred[0][0] for pred in predictions]

In [34]:
n_correct = np.sum(y_test == prediction_labels)
accuracy = float(n_correct / len(y_test))

In [36]:
n_correct

0

In [37]:
[x == y for (x, y) in zip(y_test, prediction_labels)]

[True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True]

In [38]:
num_correct = 0
for test, pred in zip(y_test, predictions):
    topn = pred[0]
    if test in topn:
        num_correct += 1

In [39]:
num_correct / len(y_test)

0.25

In [41]:
len(df_lookup_no_dups.drop_duplicates(subset="Look-up value"))

87